### ISSUE TITLE
Error scraping user page

### ISSUE THREAD

**Issue by darkcherrycreative** [YegorShtonda/strapi-plugin-instagram-feed#5]
Any ideas on this? This works on my local machine but once deployed onto a server running Plesk Obsidian (Node JS served using Passenger Phusion) all scrape requests fail with the following results:

App 2442351 output:     Error: Error scraping user page "darkcherrycreative"
App 2442351 output:     at Request._callback (/**OMMITTED**/node_modules/instagram-scraping/index.js:43:24)
App 2442351 output:     at Request.self.callback (/**OMMITTED**/node_modules/request/request.js:185:22)
App 2442351 output:     at Request.emit (events.js:200:13)
App 2442351 output:     at Request.<anonymous> (/**OMMITTED**/node_modules/request/request.js:1154:10)
App 2442351 output:     at Request.emit (events.js:200:13)
App 2442351 output:     at IncomingMessage.<anonymous> (/**OMMITTED**/node_modules/request/request.js:1076:12)
App 2442351 output:     at Object.onceWrapper (events.js:288:20)
App 2442351 output:     at IncomingMessage.emit (events.js:205:15)
App 2442351 output:     at endReadableNT (_stream_readable.js:1154:12)
App 2442351 output:     at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by YegorShtonda** [comment]
I have the same problem. Instagram blocks requests from one ip address. I was able to decide by running scraping once a day.

**Comment by YegorShtonda** [comment]
I want to add the ability to add a proxies, but I can't find time for this

**Comment by darkcherrycreative** [comment]
Proxy option would be great. The problem is compounded for me as i've got several different sites all running Strapi with the plugin, all requests come from the same IP address so none of the feeds ever get updated.

**Comment by YegorShtonda** [comment]
I will add proxy support today

**Comment by darkcherrycreative** [comment]
Did you have any luck when adding proxies to this? Did it help?
